<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE mpstruc [
  <!ELEMENT mpstruc (caption,groups*)>
  <!ATTLIST mpstruc createdBy CDATA #REQUIRED>
  <!ATTLIST mpstruc maintainedBy CDATA #REQUIRED>
  <!ATTLIST mpstruc copyright CDATA #REQUIRED>
  <!ATTLIST mpstruc url CDATA #REQUIRED>
  <!ATTLIST mpstruc lastNewProteinDate CDATA #REQUIRED>
  <!ATTLIST mpstruc lastDatabaseEditDate CDATA #REQUIRED>
  <!ATTLIST mpstruc timeStamp CDATA #REQUIRED>
  <!ELEMENT caption (#PCDATA)>
  <!ELEMENT groups (group*)>
  <!ELEMENT group (name,proteins,subgroups)>
  <!ELEMENT subgroups (subgroup*)>
  <!ELEMENT subgroup (name,proteins)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT proteins (protein*)>
  <!ELEMENT memberProteins (memberProtein*)>
  <!ELEMENT protein (pdbCode,name,species,taxonomicDomain,expressedInSpecies,resolution,description,bibliography,
                     secondaryBibliographies,relatedPdbEntries,memberProteins)>
  <!ELEMENT memberProtein (pdbCode,masterProteinPdbCode,name,species,expressedInSpecies,resolution,
                           description,bibliography,secondaryBibliographies,relatedPdbEntries)>
  <!ELEMENT pdbCode (#PCDATA)>
  <!ELEMENT masterProteinPdbCode (#PCDATA)>
  <!ELEMENT species (#PCDATA)>
  <!ELEMENT taxonomicDomain (#PCDATA)>
  <!ELEMENT expressedInSpecies (#PCDATA)>
  <!ELEMENT resolution (#PCDATA)>
  <!ELEMENT description (#PCDATA)>
  <!ELEMENT bibliography (pubMedId,authors,year,title,journal,volume,issue,pages,doi,notes)>
  <!ELEMENT pubMedId (#PCDATA)>
  <!ELEMENT authors (#PCDATA)>
  <!ELEMENT year (#PCDATA)>
  <!ELEMENT title (#PCDATA)>
  <!ELEMENT journal (#PCDATA)>
  <!ELEMENT volume (#PCDATA)>
  <!ELEMENT issue (#PCDATA)>
  <!ELEMENT pages (#PCDATA)>
  <!ELEMENT doi (#PCDATA)>
  <!ELEMENT notes (#PCDATA)>
  <!ELEMENT secondaryBibliographies (bibliography*)>
  <!ELEMENT relatedPdbEntries (pdbCode*)>
]>
<mpstruc createdBy='Stephen White' maintainedBy='Craig Snider' copyright='Copyright Â© 1998-2020 Stephen H. White. All rights reserved.' url='https://blanco.biomol.uci.edu/mpstruc/listAll/mpstrucTblXml' lastNewProteinDate='2020-09-20 21:26:21.0' lastDatabaseEditDate='2020-09-20 21:29:30.0' timeStamp='Mon Sep 21 04:50:48 PDT 2020'>
  <caption>mpstruc database</caption>
  <groups>
    <group>
      <name>MONOTOPIC MEMBRANE PROTEINS</name>
      <proteins />
      <subgroups>
        <subgroup>
          <name>Cyclooxygenases</name>
          <proteins>
            <protein>
              <pdbCode>1PRH</pdbCode>
              <name>Ram Prostaglandin H2 synthase-1 (cyclooxygenase-1 or COX-1)</name>
              <species>Ovis aries</species>
              <taxonomicDomain>Eukaryota</taxonomicDomain>
              <expressedInSpecies />
              <resolution>3.5</resolution>
              <description></description>
              <bibliography>
                <pubMedId>8121489</pubMedId>
                <authors>Picot D, Loll PJ, &amp;amp; Garavito RM</authors>
                <year>1994</year>
                <title>The x-ray crystal structure of the membrane protein prostaglandin H&lt;sub&gt;2&lt;/sub&gt;synthase-1.</title>
                <journal>Nature</journal>
                <volume>367</volume>
                <issue />
                <pages>243-249</pages>
                <doi></doi>
                <notes></notes>
              </bibliography>
              <secondaryBibliographies />
              <relatedPdbEntries />
              <memberProteins>
                <memberProtein>
                  <pdbCode>1PTH</pdbCode>
                  <masterProteinPdbCode>1PRH</masterProteinPdbCode>
                  <name>Ram Prostaglandin H2 synthase-1 (COX-1)</name>
                  <species>Ovis aries</species>
                  <taxonomicDomain>Eukaryota</taxonomicDomain>
                  <expressedInSpecies></expressedInSpecies>
                  <resolution>3.4</resolution>
                  <description>In complex with bromoaspirin.</description>
                  <bibliography>
                    <pubMedId>7552725</pubMedId>
                    <authors>Loll PJ, Picot D, &amp;amp; Garavito RM</authors>
                    <year>1995</year>
                    <title>The structural basis of aspirin activity inferred from the crystal structure of inactivated prostaglandin H2 synthase.</title>
                    <journal>Nat Struct Biol</journal>
                    <volume>2</volume>
                    <issue />
                    <pages>637-643</pages>
                    <doi></doi>
                    <notes></notes>
                  </bibliography>
                  <secondaryBibliographies />
                  <relatedPdbEntries />
                </memberProtein>
                <memberProtein>
                  <pdbCode>1CQE</pdbCode>
                  <masterProteinPdbCode>1PRH</masterProteinPdbCode>
                  <name>Ram Prostaglandin H2 synthase-1 (COX-1)</name>
                  <species>Ovis aries</species>
                  <taxonomicDomain>Eukaryota</taxonomicDomain>
                  <expressedInSpecies></expressedInSpecies>
                  <resolution>3.1</resolution>
                  <description>In complex with flurbiprofen.</description>
                  <bibliography>
                    <pubMedId>7732912</pubMedId>
                    <authors>Garavito RM, Picot D, &amp;amp; Loll PJ</authors>
                    <year>1995</year>
                    <title>The 3.1 A X-ray crystal structure of the integral membrane enzyme prostaglandin H2 synthase-1.</title>
                    <journal>Adv Prostaglandin Thromboxane Leukot Res</journal>
                    <volume>23</volume>
                    <issue />
                    <pages>99-103</pages>
                    <doi></doi>
                    <notes></notes>
                  </bibliography>
                  <secondaryBibliographies />
                  <relatedPdbEntries />
                </memberProtein>
                <memberProtein>
                  <pdbCode>1EQG</pdbCode>
                  <masterProteinPdbCode>1PRH</masterProteinPdbCode>
                  <name>Ram Prostaglandin H2 synthase-1 (COX-1)</name>
                  <species>Ovis aries</species>
                  <taxonomicDomain>Eukaryota</taxonomicDomain>
                  <expressedInSpecies></expressedInSpecies>
                  <resolution>2.61</resolution>
                  <description>1EQG is complex with ibuprofen. &lt;br /&gt; Complex with flurbiprofen, 2.70&amp;nbsp;&amp;Aring;: 1EQH &lt;br /&gt; Complex with flurbiprofen methyl ester, 2.75&amp;nbsp;&amp;Aring;: 1HT5 &lt;br /&gt; Complex with alclofenac, 2.69&amp;nbsp;&amp;Aring;: 1HT8</description>
                  <bibliography>
                    <pubMedId>11318639</pubMedId>
                    <authors>Selinsky BS, Gupta K, Sharkey CT, Loll PJ</authors>
                    <year>2001</year>
                    <title>Structural analysis of NSAID binding by prostaglandin H2 synthase: time-dependent and time-independent inhibitors elicit identical enzyme conformations.</title>
                    <journal>Biochemistry</journal>
                    <volume>40</volume>
                    <issue />
                    <pages>5172-5180</pages>
                    <doi></doi>
                    <notes></notes>
                  </bibliography>
                  <secondaryBibliographies />
                  <relatedPdbEntries>
                    <pdbCode>1HT8</pdbCode>
                    <pdbCode>1HT5</pdbCode>
                    <pdbCode>1EQH</pdbCode>
                  </relatedPdbEntries>
                </memberProtein>
                <memberProtein>
                  <pdbCode>1EBV</pdbCode>
                  <masterProteinPdbCode>1PRH</masterProteinPdbCode>
                  <name>Ram Prostaglandin H2 synthase-1 (COX-1)</name>
                  <species>Ovis aries</species>
                  <taxonomicDomain>Eukaryota</taxonomicDomain>
                  <expressedInSpecies></expressedInSpecies>
                  <resolution>3.2</resolution>
                  <description>In complex with O-actylsalicylhydroxamic acid.</description>
                  <bibliography>
                    <pubMedId>11723249</pubMedId>
                    <authors>Loll PJ, Sharkey CT, O&amp;apos;Connor SJ, Dooley CM, O&amp;apos;Brien E, Devocelle M, Nolan KB, Selinsky BS, &amp;amp; Fitzgerald DJ</authors>
                    <year>2001</year>
                    <title>O-acetylsalicylhydroxamic acid, a novel acetylating inhibitor of prostaglandin H2 synthase: structural and functional characterization of enzyme-inhibitor interactions.</title>
                    <journal>Mol Pharmacol</journal>
                    <volume>60</volume>
                    <issue />
                    <pages>1407-1413</pages>
                    <doi></doi>
                    <notes></notes>
                  </bibliography>
                  <secondaryBibliographies />
                  <relatedPdbEntries />
                </memberProtein>
                <memberProtein>
                  <pdbCode>1Q4G</pdbCode>
                  <masterProteinPdbCode>1PRH</masterProteinPdbCode>
                  <name>Ram Prostaglandin H2 synthase-1 (COX-1)</name>
                  <species>Ovis aries</species>
                  <taxonomicDomain>Eukaryota</taxonomicDomain>
                  <expressedInSpecies></expressedInSpecies>
                  <resolution>2.00</resolution>
                  <description>In complex with alpha-methyl-4-biphenyl acetic acid.</description>
                  <bibliography>
                    <pubMedId>14672659</pubMedId>
                    <authors>Gupta K, Selinsky BS, Kaub CJ, Katz AK, &amp;amp; Loll PJ</authors>
                    <year>2004</year>
                    <title>The 2.0 &amp;Aring; resolution crystal structure of prostaglandin H2 synthase-1: structural insights into an unusual peroxidase.</title>
                    <journal>J Mol Biol</journal>
                    <volume>335</volume>
                    <issue />
                    <pages>503-518</pages>
                    <doi></doi>
                    <notes></notes>
                  </bibliography>
                  <secondaryBibliographies />
                  <relatedPdbEntries />
                </memberProtein>
                <memberProtein>
                  <pdbCode>2AYL</pdbCode>
                  <masterProteinPdbCode>1PRH</masterProteinPdbCode>
                  <name>Ram Prostaglandin H2 synthase-1 (COX-1)</name>
                  <species>Ovis aries</species>
                  <taxonomicDomain>Eukaryota</taxonomicDomain>
                  <expressedInSpecies></expressedInSpecies>
                  <resolution>2.00</resolution>
                  <description>In complex with flurbiprofen + Mn(III) PPIX cofactor.</description>
                  <bibliography>
                    <pubMedId>16421446</pubMedId>
                    <authors>Gupta K, Selinsky BS, &amp;amp; Loll PJ</authors>
                    <year>2006</year>
                    <title>2.0 angstroms structure of prostaglandin H2 synthase-1 reconstituted with a manganese porphyrin cofactor.</title>
                    <journal>Acta Crystallogr D Biol Crystallogr</journal>
                    <volume>62</volume>
                    <issue />
                    <pages>151-156</pages>
                    <doi></doi>
                    <notes></notes>
                  </bibliography>
                  <secondaryBibliographies />
                  <relatedPdbEntries />
                </memberProtein>
                <memberProtein>
                  <pdbCode>3N8V</pdbCode>
                  <masterProteinPdbCode>1PRH</masterProteinPdbCode>
                  <name>Ram Prostaglandin H2 synthase-1 (COX-1)</name>
                  <species>Ovis aries</species>
                  <taxonomicDomain>Eukaryota</taxonomicDomain>
                  <expressedInSpecies>Spodoptera frugiperda</expressedInSpecies>
                  <resolution>3.05</resolution>
                  <description>3N8V is the unoccupied structure. &lt;br /&gt;R120Q/Native Heterodimer mutant in complex with Flurbiprofen, 2.75&amp;nbsp;&amp;Aring;: 3N8W &lt;br /&gt;COX-1 in complex with Nimesulide, 2.75&amp;nbsp;&amp;Aring;: 3N8X &lt;br /&gt;Aspirin Acetylated COX-1 in Complex with Diclofenac, 2.60&amp;nbsp;&amp;Aring;: 3N8Y &lt;br /&gt;COX-1 in Complex with Flurbiprofen, 2.90&amp;nbsp;&amp;Aring;: 3N8Z</description>
                  <bibliography>
                    <pubMedId>20669977</pubMedId>
                    <authors>Sidhu RS, Lee JY, Yuan C, &amp;amp; Smith WL</authors>
                    <year>2010</year>
                    <title>Comparison of Cyclooxygenase-1 Crystal Structures: Cross-Talk between Monomers Comprising Cyclooxygenase-1 Homodimers.</title>
                    <journal>Biochemistry</journal>
                    <volume>49</volume>
                    <issue />
                    <pages>7069-7079</pages>
                    <doi></doi>
                    <notes></notes>
                  </bibliography>
                  <secondaryBibliographies />
                  <relatedPdbEntries>
                    <pdbCode>3N8Y</pdbCode>
                    <pdbCode>3N8X</pdbCode>
                    <pdbCode>3N8W</pdbCode>
                    <pdbCode>3N8Z</pdbCode>
                  </relatedPdbEntries>
                </memberProtein>
              </memberProteins>
            </protein>
            <protein>
              <pdbCode>1CX2</pdbCode>
              <name>Cyclooxygenase-2</name>
              <species>Mus musculus</species>
              <taxonomicDomain>Eukaryota</taxonomicDomain>
              <expressedInSpecies />
              <resolution>3.0</resolution>
              <description></description>
              <bibliography>
                <pubMedId>8967954</pubMedId>
                <authors>Kurumbail RG, Stevens AM, Gierse JK, McDonald JJ, Stegeman RA, Pak JY, Gildehaus D, Miyashiro JM, Penning TD, Seibert, K et al</authors>
                <year>1996</year>
                <title>Structural basis for selective inhibition of cyclooxygenase-2 by anti-inflammatory agents.</title>
                <journal>Nature</journal>
                <volume>384</volume>
                <issue />
                <pages>644-648</pages>
                <doi></doi>
                <notes></notes>
              </bibliography>
              <secondaryBibliographies />
              <relatedPdbEntries />
              <memberProteins>
                <memberProtein>
                  <pdbCode>6BL4</pdbCode>
                  <masterProteinPdbCode>1CX2</masterProteinPdbCode>
                  <name>Cyclooxygenase-2 with bound indomethacin-ethylenediamine-dansyl conjugate</name>
                  <species>Mus musculus</species>
                  <taxonomicDomain>Eukaryota</taxonomicDomain>
                  <expressedInSpecies>S. frugiperda</expressedInSpecies>
                  <resolution>2.22</resolution>
                  <description>with bound indomethacin-butyldiamine-dansyl conjugate, 2.22 &amp;Aring;: 6BL3</description>
                  <bibliography>
                    <pubMedId>31000626</pubMedId>
                    <authors>Xu S, Uddin MJ, Banerjee S, Duggan K, Musee J, Kiefer JR, Ghebreselasie K, Rouzer CA, &amp;amp; Marnett LJ</authors>
                    <year>2019</year>
                    <title>Fluorescent indomethacin-dansyl conjugates utilize the membrane-binding domain of cyclooxygenase-2 to block the opening to the active site.</title>
                    <journal>J Biol Chem</journal>
                    <volume>294</volume>
                    <issue>22</issue>
                    <pages>8690-8698</pages>
                    <doi>10.1074/jbc.RA119.007405</doi>
                    <notes></notes>
                  </bibliography>
                  <secondaryBibliographies />
                  <relatedPdbEntries />
                </memberProtein>
              </memberProteins>
            </protein>
            <protein>
              <pdbCode>4HHS</pdbCode>
              <name>Fatty acid &amp;alpha;-dioxygenase (&amp;alpha;-DOX)</name>
              <species>Arabidopsis thaliana </species>
              <taxonomicDomain>Eukaryota</taxonomicDomain>
              <expressedInSpecies>E. coli</expressedInSpecies>
              <resolution>1.70</resolution>
              <description>First structure of a member of the &amp;alpha;-DOX subfamily of cyclooxygenase-perixidase family of heme-containing proteins.&lt;br /&gt;
With bound imidazole, 1.51 &amp;Aring;: 4HHR</description>
              <bibliography>
                <pubMedId>23373518</pubMedId>
                <authors>Goulah CC, Zhu G, Koszelak-Rosenblum M, &amp;amp; Malkowski MG</authors>
                <year>2013</year>
                <title>The Crystal Structure of &amp;alpha;-Dioxygenase Provides Insight into Diversity in the Cyclooxygenase-Peroxidase Superfamily.</title>
                <journal>Biochemistry</journal>
                <volume>52</volume>
                <issue />
                <pages>1364-1372</pages>
                <doi>10.1021/bi400013k</doi>
                <notes />
              </bibliography>
              <secondaryBibliographies />
              <relatedPdbEntries>
                <pdbCode>4HHR</pdbCode>
              </relatedPdbEntries>
              <memberProteins />
            </protein>
          </proteins>
        </subgroup>
        <subgroup>
          <name>Lipoxygenases</name>
          <proteins>
            <protein>
              <pdbCode>2SBL</pdbCode>
              <name>Arachidonic acid 15-lipoxygenase from soybeans</name>
              <species>Glycine max</species>
              <taxonomicDomain>Eukaryota</taxonomicDomain>
              <expressedInSpecies />
              <resolution>2.60</resolution>
              <description></description>
              <bibliography>
                <pubMedId>8502991</pubMedId>
                <authors>Boyington JC, Gaffney BJ, &amp;amp; Amzel LM</authors>
                <year>1993</year>
                <title>The three-dimensional structure of an arachidonic acid 15-lipoxygenase.</title>
                <journal>Science</journal>
                <volume>260</volume>
                <issue>5113</issue>
                <pages>1482-1486</pages>
                <doi>10.1126/science.8502991</doi>
                <notes />
              </bibliography>
              <secondaryBibliographies />
              <relatedPdbEntries />
              <memberProteins />
            </protein>
            <protein>
              <pdbCode>1YGE</pdbCode>
              <name>Lipoxygenase-L1 from soybeans</name>
              <species>Glycine max</species>
              <taxonomicDomain>Eukaryota</taxonomicDomain>
              <expressedInSpecies />
              <resolution>1.40</resolution>
              <description></description>
              <bibliography>
                <pubMedId>8718858</pubMedId>
                <authors>Minor W, Steczko J, Stec B, Otwinowski Z, Bolin JT, Walter R, &amp;amp; Axelrod B</authors>
                <year>1996</year>
                <title>Crystal structure of soybean lipoxygenase L-1 at 1.4 A resolution.</title>
                <journal>Biochemistry</journal>
                <volume>35</volume>
                <issue>33</issue>
                <pages>10687-10701</pages>
                <doi>10.1021/bi960576u</doi>
                <notes />
              </bibliography>
              <secondaryBibliographies />
              <relatedPdbEntries />
              <memberProteins />
            </protein>
            <protein>
              <pdbCode>1LNH</pdbCode>
              <name>Lipoxygenase-L3 from soybeans</name>
              <species>Glycine max</species>
              <taxonomicDomain>Eukaryota</taxonomicDomain>
              <expressedInSpecies />
              <resolution>2.60</resolution>
              <description></description>
              <bibliography>
                <pubMedId>9294864</pubMedId>
                <authors>Skrzypczak-Jankun E, Amzel LM, Kroa BA, &amp;amp; Funk MO Jr</authors>
                <year>1997</year>
                <title>Structure of soybean lipoxygenase L3 and a comparison with its L1 isoenzyme.</title>
                <journal>Proteins</journal>
                <volume>29</volume>
                <issue>1</issue>
                <pages>15-31</pages>
                <doi>10.1002/(SICI)1097-0134(199709)29:1</doi>
                <notes />
              </bibliography>
              <secondaryBibliographies />
              <relatedPdbEntries />
              <memberProteins />
            </protein>
            <protein>
              <pdbCode>2FNQ</pdbCode>
              <name>8R-Lipoxygenase from coral</name>
              <species>Plexaura homomalla</species>
              <taxonomicDomain>Eukaryota</taxonomicDomain>
              <expressedInSpecies>E. coli</expressedInSpecies>
              <resolution>3.20</resolution>
              <description>2FNQ supersedes 1ZQ4</description>
              <bibliography>
                <pubMedId>16162493</pubMedId>
                <authors>Oldham ML, Brash AR, &amp;amp; Newcomer ME</authors>
                <year>2005</year>
                <title>Insights from the X-ray crystal structure of coral 8R-lipoxygenase: calcium activation via a C2-like domain and a structural basis of product chirality.</title>
                <journal>J Biol Chem</journal>
                <volume>280</volume>
                <issue>47</issue>
                <pages>39545-39552</pages>
                <doi>10.1074/jbc.M506675200</doi>
                <notes />
              </bibliography>
              <secondaryBibliographies />
              <relatedPdbEntries />
              <memberProteins>
                <memberProtein>
                  <pdbCode>3FG4</pdbCode>
                  <masterProteinPdbCode>2FNQ</masterProteinPdbCode>
                  <name>8R-Lipoxygenase from coral.  &amp;Delta;413-417 I805A mutant</name>
                  <species>Plexaura homomalla</species>
                  <taxonomicDomain>Eukaryota</taxonomicDomain>
                  <expressedInSpecies>E. coli</expressedInSpecies>
                  <resolution>1.85</resolution>
                  <description></description>
                  <bibliography>
                    <pubMedId>19594169</pubMedId>
                    <authors>Neau DB, Gilbert NC, Bartlett SG, Boeglin W, Brash AR, &amp;amp; Newcomer ME</authors>
                    <year>2009</year>
                    <title>The 1.85 A structure of an 8R-lipoxygenase suggests a general model for lipoxygenase product specificity.</title>
                    <journal>Biochemistry</journal>
                    <volume>48</volume>
                    <issue>33</issue>
                    <pages>7906-7915</pages>
                    <doi>10.1021/bi900084m</doi>
                    <notes />
                  </bibliography>
                  <secondaryBibliographies />
                  <relatedPdbEntries />
                </memberProtein>
              </memberProteins>
            </protein>
            <protein>
              <pdbCode>1LOX</pdbCode>
              <name>15-Lipoxygenase from rabbit reticulocytes</name>
              <species>Oryctolagus cuniculus</species>
              <taxonomicDomain>Eukaryota</taxonomicDomain>
              <expressedInSpecies />
              <resolution>2.40</resolution>
              <description></description>
              <bibliography>
                <pubMedId>9406550</pubMedId>
                <authors>Gillmor SA, Villase&amp;ntilde;or A, Fletterick R, Sigal E, &amp;amp; Browner MF</authors>
                <year>1997</year>
                <title>The structure of mammalian 15-lipoxygenase reveals similarity to the lipases and the determinants of substrate specificity.</title>
                <journal>Nat Struct Mol Biol</journal>
                <volume>4</volume>
                <issue>12</issue>
                <pages>1003-1009</pages>
                <doi>10.1038/nsb1297-1003 </doi>
                <notes />
              </bibliography>
              <secondaryBibliographies />
              <relatedPdbEntries />
              <memberProteins />
            </protein>
            <protein>
              <pdbCode>3O8Y</pdbCode>
              <name>5-Lipoxygenase</name>
              <species>Homo sapiens</species>
              <taxonomicDomain>Eukaryota</taxonomicDomain>
              <expressedInSpecies>E. coli</expressedInSpecies>
              <resolution>2.39</resolution>
              <description></description>
              <bibliography>
                <pubMedId>21233389</pubMedId>
                <authors>Gilbert NC, Bartlett SG, Waight MT, Neau DB, Boeglin WE, Brash AR, &amp;amp; Newcomer ME</authors>
                <year>2011</year>
                <title>The structure of human 5-lipoxygenase.</title>
                <journal>Science</journal>
                <volume>331</volume>
                <issue />
                <pages>217-219</pages>
                <doi>10.1126/science.1197203</doi>
                <notes />
              </bibliography>
              <secondaryBibliographies />
              <relatedPdbEntries />
              <memberProteins />
            </protein>
            <protein>
              <pdbCode>4NRE</pdbCode>
              <name>15-Lipoxygenase-2 (15-LOX-2) with substrate mimic</name>
              <species>Homo sapiens</species>
              <taxonomicDomain>Eukaryota</taxonomicDomain>
              <expressedInSpecies>E. coli</expressedInSpecies>
              <resolution>2.63</resolution>
              <description></description>
              <bibliography>
                <pubMedId>24497644</pubMedId>
                <authors>Kobe MJ, Neau DB, Mitchell CE, Bartlett SG, &amp;amp; Newcomer ME</authors>
                <year>2014</year>
                <title>The structure of human 15-lipoxygenase-2 with a substrate mimic.</title>
                <journal>J Biol Chem</journal>
                <volume>289</volume>
                <issue />
                <pages>8562-8569</pages>
                <doi>10.1074/jbc.M113.543777</doi>
                <notes />
              </bibliography>
              <secondaryBibliographies />
              <relatedPdbEntries />
              <memberProteins />
            </protein>
          </proteins>
        </subgroup>
        <subgroup>
          <name>Squalene-Hopene Cyclases</name>
          <proteins>
            <protein>
              <pdbCode>2SQC</pdbCode>
              <name>Squalene-hopene cyclase</name>
              <species>Alicyclobacillus acidocaldarius</species>
              <taxonomicDomain>Bacteria</taxonomicDomain>
              <expressedInSpecies></expressedInSpecies>
              <resolution>2.0</resolution>
              <description> 2SQC is space group P4&lt;sub&gt;3&lt;/sub&gt;2&lt;sub&gt;1&lt;/sub&gt;2.  3SQC, 2.8&amp;nbsp;&amp;Aring; is P3&lt;sub&gt;2&lt;/sub&gt;21.</description>
              <bibliography>
                <pubMedId>9931258</pubMedId>
                <authors>Wendt KU, Lenhart A, &amp;amp; Schulz GE</authors>
                <year>1999</year>
                <title>The structure of the membrane protein squalene-hopene cyclase at 2.0 &amp;Aring; resolution.</title>
                <journal>J. Mol. Biol.</journal>
                <volume>286</volume>
                <issue />
                <pages>175-187</pages>
                <doi></doi>
                <notes></notes>
              </bibliography>
              <secondaryBibliographies />
              <relatedPdbEntries>
                <pdbCode>3SQC</pdbCode>
              </relatedPdbEntries>
              <memberProteins />
            </protein>
          </proteins>
        </subgroup>
        <subgroup>
          <name>Oxidases</name>
          <proteins>
            <protein>
              <pdbCode>1GOS</pdbCode>
              <name>Monoamine Oxidase B</name>
              <species>Homo sapiens (Human) mitochondrial outer membrane</species>
              <taxonomicDomain>Eukaryota</taxonomicDomain>
              <expressedInSpecies>Pichia pastoris</expressedInSpecies>
              <resolution>3.0</resolution>
              <description> NOTE: MAOB has a single transmembrane helix that anchors it to the outer membrane (residues 489-515). Nevertheless, we consider it monotopic because the bulk of the 520-residue protein, including the active site, is not located within the membrane core.</description>
              <bibliography>
                <pubMedId>11753429</pubMedId>
                <authors>Binda C, Newton-Vinson P, HubÃ¡lek F, Edmondson DE, &amp;amp; Mattevi A</authors>
                <year>2002</year>
                <title>Structure of human monoamine oxidase B, a drug target for the treatment of neurological disorders.</title>
                <journal>Nature Struct Biol</journal>
                <volume>9</volume>
                <issue />
                <pages>22-26</pages>
                <doi></doi>
                <notes></notes>
              </bibliography>
              <secondaryBibliographies />
              <relatedPdbEntries />
              <memberProteins>
                <memberProtein>
                  <pdbCode>1OJA</pdbCode>
                  <masterProteinPdbCode>1GOS</masterProteinPdbCode>
                  <name>Monoamine Oxidase B with bound Isatin</name>
                  <species>Homo sapiens (Human) mitochondrial outer membrane</species>
                  <taxonomicDomain>Eukaryota</taxonomicDomain>
                  <expressedInSpecies>Pichia pastoris</expressedInSpecies>
                  <resolution>1.70</resolution>